# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'questions.ui'
#
# Created: Mon Oct 18 10:17:27 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(888, 682)
        self.didPython = QtGui.QCheckBox(Form)
        self.didPython.setGeometry(QtCore.QRect(30, 220, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.didPython.setFont(font)
        self.didPython.setObjectName("didPython")
        self.didSML = QtGui.QCheckBox(Form)
        self.didSML.setGeometry(QtCore.QRect(130, 220, 85, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.didSML.setFont(font)
        self.didSML.setObjectName("didSML")
        self.didRuby = QtGui.QCheckBox(Form)
        self.didRuby.setGeometry(QtCore.QRect(230, 220, 85, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.didRuby.setFont(font)
        self.didRuby.setObjectName("didRuby")
        self.didPHP = QtGui.QCheckBox(Form)
        self.didPHP.setGeometry(QtCore.QRect(320, 220, 85, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.didPHP.setFont(font)
        self.didPHP.setObjectName("didPHP")
        self.didHTML = QtGui.QCheckBox(Form)
        self.didHTML.setGeometry(QtCore.QRect(230, 250, 85, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.didHTML.setFont(font)
        self.didHTML.setObjectName("didHTML")
        self.didC = QtGui.QCheckBox(Form)
        self.didC.setGeometry(QtCore.QRect(130, 250, 85, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.didC.setFont(font)
        self.didC.setObjectName("didC")
        self.didJava = QtGui.QCheckBox(Form)
        self.didJava.setGeometry(QtCore.QRect(30, 250, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.didJava.setFont(font)
        self.didJava.setObjectName("didJava")
        self.didJavascript = QtGui.QCheckBox(Form)
        self.didJavascript.setGeometry(QtCore.QRect(320, 250, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.didJavascript.setFont(font)
        self.didJavascript.setObjectName("didJavascript")
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(320, 590, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: #99f;")
        self.pushButton.setObjectName("pushButton")
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 190, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 300, 891, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.didOther = QtGui.QCheckBox(Form)
        self.didOther.setGeometry(QtCore.QRect(450, 220, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.didOther.setFont(font)
        self.didOther.setObjectName("didOther")
        self.didOtherWhat = QtGui.QLineEdit(Form)
        self.didOtherWhat.setGeometry(QtCore.QRect(450, 250, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.didOtherWhat.setFont(font)
        self.didOtherWhat.setObjectName("didOtherWhat")
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 330, 501, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 440, 581, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(30, 460, 511, 111))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.radioButton_4 = QtGui.QRadioButton(self.frame)
        self.radioButton_4.setGeometry(QtCore.QRect(120, 120, 99, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_2 = QtGui.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(210, 120, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtGui.QRadioButton(self.frame)
        self.radioButton_3.setGeometry(QtCore.QRect(350, 120, 99, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setStrikeOut(False)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setAutoExclusive(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton = QtGui.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(10, 120, 99, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.isNew = QtGui.QRadioButton(self.frame)
        self.isNew.setGeometry(QtCore.QRect(10, 10, 99, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.isNew.setFont(font)
        self.isNew.setChecked(True)
        self.isNew.setObjectName("isNew")
        self.isSmall = QtGui.QRadioButton(self.frame)
        self.isSmall.setGeometry(QtCore.QRect(130, 10, 99, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.isSmall.setFont(font)
        self.isSmall.setObjectName("isSmall")
        self.isOK = QtGui.QRadioButton(self.frame)
        self.isOK.setGeometry(QtCore.QRect(250, 10, 99, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.isOK.setFont(font)
        self.isOK.setObjectName("isOK")
        self.isGood = QtGui.QRadioButton(self.frame)
        self.isGood.setGeometry(QtCore.QRect(370, 10, 99, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.isGood.setFont(font)
        self.isGood.setObjectName("isGood")
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(130, 30, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 100, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.age = QtGui.QSpinBox(Form)
        self.age.setGeometry(QtCore.QRect(30, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.age.setFont(font)
        self.age.setMinimum(16)
        self.age.setProperty("value", 18)
        self.age.setObjectName("age")
        self.sex = QtGui.QComboBox(Form)
        self.sex.setGeometry(QtCore.QRect(130, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sex.setFont(font)
        self.sex.setObjectName("sex")
        self.sex.addItem("")
        self.sex.setItemText(0, "")
        self.sex.addItem("")
        self.sex.addItem("")
        self.mainSubject = QtGui.QLineEdit(Form)
        self.mainSubject.setGeometry(QtCore.QRect(30, 120, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mainSubject.setFont(font)
        self.mainSubject.setObjectName("mainSubject")
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(260, 30, 441, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.enrolled = QtGui.QComboBox(Form)
        self.enrolled.setGeometry(QtCore.QRect(260, 50, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.enrolled.setFont(font)
        self.enrolled.setObjectName("enrolled")
        self.enrolled.addItem("")
        self.enrolled.addItem("")
        self.enrolled.addItem("")
        self.enrolled.addItem("")
        self.enrolled.addItem("")
        self.enrolled.addItem("")
        self.enrolled.addItem("")
        self.didYears = QtGui.QComboBox(Form)
        self.didYears.setGeometry(QtCore.QRect(30, 360, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.didYears.setFont(font)
        self.didYears.setStyleSheet("None")
        self.didYears.setObjectName("didYears")
        self.didYears.addItem("")
        self.didYears.addItem("")
        self.didYears.addItem("")
        self.didYears.addItem("")
        self.didYears.addItem("")
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(0, 410, 891, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(0, 160, 891, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.retranslateUi(Form)
        self.sex.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.didPython.setText(QtGui.QApplication.translate("Form", "Python", None, QtGui.QApplication.UnicodeUTF8))
        self.didSML.setText(QtGui.QApplication.translate("Form", "SML", None, QtGui.QApplication.UnicodeUTF8))
        self.didRuby.setText(QtGui.QApplication.translate("Form", "Ruby", None, QtGui.QApplication.UnicodeUTF8))
        self.didPHP.setText(QtGui.QApplication.translate("Form", "PHP", None, QtGui.QApplication.UnicodeUTF8))
        self.didHTML.setText(QtGui.QApplication.translate("Form", "HTML", None, QtGui.QApplication.UnicodeUTF8))
        self.didC.setText(QtGui.QApplication.translate("Form", "C/C++", None, QtGui.QApplication.UnicodeUTF8))
        self.didJava.setText(QtGui.QApplication.translate("Form", "Java/C#", None, QtGui.QApplication.UnicodeUTF8))
        self.didJavascript.setText(QtGui.QApplication.translate("Form", "Javascript", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "START!", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Hvilke sprog har du kodet i?", None, QtGui.QApplication.UnicodeUTF8))
        self.didOther.setText(QtGui.QApplication.translate("Form", "Andet/andre:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Hvor mange års erfaring har du med programmering?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Hvordan vurderer du dit niveau ift. programmering?", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("Form", "Øvet", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("Form", "Kompetent", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("Form", "Ekspert", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("Form", "Begynder", None, QtGui.QApplication.UnicodeUTF8))
        self.isNew.setText(QtGui.QApplication.translate("Form", "Begynder", None, QtGui.QApplication.UnicodeUTF8))
        self.isSmall.setText(QtGui.QApplication.translate("Form", "Let øvet", None, QtGui.QApplication.UnicodeUTF8))
        self.isOK.setText(QtGui.QApplication.translate("Form", "Erfaren", None, QtGui.QApplication.UnicodeUTF8))
        self.isGood.setText(QtGui.QApplication.translate("Form", "Ekspert", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Alder:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Køn:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Hovedfag:", None, QtGui.QApplication.UnicodeUTF8))
        self.sex.setItemText(1, QtGui.QApplication.translate("Form", "Mand", None, QtGui.QApplication.UnicodeUTF8))
        self.sex.setItemText(2, QtGui.QApplication.translate("Form", "Kvinde", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Studietid:", None, QtGui.QApplication.UnicodeUTF8))
        self.enrolled.setItemText(0, QtGui.QApplication.translate("Form", "Startet i år", None, QtGui.QApplication.UnicodeUTF8))
        self.enrolled.setItemText(1, QtGui.QApplication.translate("Form", "1 år", None, QtGui.QApplication.UnicodeUTF8))
        self.enrolled.setItemText(2, QtGui.QApplication.translate("Form", "2 år", None, QtGui.QApplication.UnicodeUTF8))
        self.enrolled.setItemText(3, QtGui.QApplication.translate("Form", "3 år", None, QtGui.QApplication.UnicodeUTF8))
        self.enrolled.setItemText(4, QtGui.QApplication.translate("Form", "4 år", None, QtGui.QApplication.UnicodeUTF8))
        self.enrolled.setItemText(5, QtGui.QApplication.translate("Form", "5 år", None, QtGui.QApplication.UnicodeUTF8))
        self.enrolled.setItemText(6, QtGui.QApplication.translate("Form", "Længere", None, QtGui.QApplication.UnicodeUTF8))
        self.didYears.setItemText(0, QtGui.QApplication.translate("Form", "Under 1 år", None, QtGui.QApplication.UnicodeUTF8))
        self.didYears.setItemText(1, QtGui.QApplication.translate("Form", "1-2 år", None, QtGui.QApplication.UnicodeUTF8))
        self.didYears.setItemText(2, QtGui.QApplication.translate("Form", "2-3 år", None, QtGui.QApplication.UnicodeUTF8))
        self.didYears.setItemText(3, QtGui.QApplication.translate("Form", "3-5 år", None, QtGui.QApplication.UnicodeUTF8))
        self.didYears.setItemText(4, QtGui.QApplication.translate("Form", "Mere end 5 år", None, QtGui.QApplication.UnicodeUTF8))

